# Generated by Django 4.2.6 on 2023-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="none", upload_to=""),
        ),
    ]
