# Generated by Django 4.2.6 on 2023-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson2", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="none", upload_to="products/"),
        ),
    ]
