# Generated by Django 4.2.6 on 2023-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson2", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="none"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="none", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
